from django.contrib.auth.models import User
from django.test import TestCase

from .models import EducationLevel, Subject, Topic, TopicProgress


class SyllabusModelTests(TestCase):
    def setUp(self):
        self.level = EducationLevel.objects.create(code="JCE", name="Junior Certificate Examination", order=2)
        self.subject = Subject.objects.create(education_level=self.level, name="Mathematics")
        self.topic = Topic.objects.create(subject=self.subject, title="Algebra", learning_objectives="Solve equations\nSimplify expressions")

    def test_subject_slug_autogenerated(self):
        self.assertEqual(self.subject.slug, "mathematics")

    def test_topic_slug_autogenerated(self):
        self.assertEqual(self.topic.slug, "algebra")

    def test_objectives_list_parses_lines(self):
        self.assertEqual(self.topic.objectives_list(), ["Solve equations", "Simplify expressions"])

    def test_topic_progress_default_not_started(self):
        user = User.objects.create_user(username="u1", password="pass12345")
        progress, created = TopicProgress.objects.get_or_create(user=user, topic=self.topic)
        self.assertEqual(progress.status, TopicProgress.NOT_STARTED)

    def test_subject_unique_slug_per_level(self):
        with self.assertRaises(Exception):
            Subject.objects.create(education_level=self.level, name="Mathematics")
